const BELTS=[{id:"white",name:"White",color:"#f4f0ea",skill:"Add/sub to 20",free:true},{id:"yellow",name:"Yellow",color:"#ffd84a",skill:"×1 to ×5",free:true},{id:"orange",name:"Orange",color:"#ff7a18",skill:"×6 to ×9",free:false},{id:"green",name:"Green",color:"#2ecc71",skill:"×10–×12",free:false},{id:"blue",name:"Blue",color:"#3498db",skill:"Division",free:false},{id:"purple",name:"Purple",color:"#9b59b6",skill:"Fractions",free:false},{id:"brown",name:"Brown",color:"#8d5a2b",skill:"Multi-digit",free:false},{id:"black",name:"Black",color:"#222",skill:"Grandmaster",free:false}];
const AVATARS=["🐯","🐲","🐺"];
const DROPS=[{id:"mat-red",name:"Crimson Mat",when:"Week 1",ground:"#5a1420",desc:"Launch floor."},{id:"gi-gold",name:"Gold Gi",when:"Week 3",ground:"#4a3208",desc:"After 5 stamps."},{id:"mat-night",name:"Night Dojo",when:"Week 5",ground:"#0b1020",desc:"Blue lanterns."},{id:"gi-dragon",name:"Dragon Scale Gi",when:"Week 7",ground:"#123018",desc:"Green belt drop."},{id:"mat-arena",name:"Tournament Arena",when:"Week 9",ground:"#3a1028",desc:"Spar nights."},{id:"gi-grand",name:"Grandmaster Gi",when:"Week 12",ground:"#1a1a1a",desc:"Black belt look."}];
const KEY="beltup-dojo-v1";
function blankFacts(){const f={};for(let a=0;a<=20;a++)for(let b=0;b<=20;b++){if(a+b<=20)f["A:"+a+"+"+b]=0;if(a>=b)f["S:"+a+"-"+b]=0;}for(let a=1;a<=12;a++)for(let b=1;b<=12;b++)f["M:"+a+"x"+b]=0;return f;}
function newKid(name,avatar){return{name,avatar,belt:"yellow",facts:blankFacts(),minutes:0,sessions:[],stamps:{},comboBest:0,drop:"mat-red"};}
function load(){try{const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw);}catch(e){}return{pin:"1234",kids:[newKid("Andres","🐯")],active:0,onboarded:true};}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
let state=load();
if(!state.kids||!state.kids.length)state.kids=[newKid("Andres","🐯")];
if(state.kids.length===1&&!state.kids[0].name)state.kids[0].name="Andres";
state.onboarded=true;save();
let play=null;
function kid(){return state.kids[state.active];}
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"));document.getElementById(id).classList.add("on");if(id==="home")renderHome();if(id==="editKids")renderEdit();if(id==="sparSetup")renderSparSetup();if(id==="parent")renderParent();if(id==="onboard")renderOnboard();if(id==="drops")renderDrops();}
function renderOnboard(){const wrap=document.getElementById("onAvatars");if(!wrap)return;wrap.innerHTML=AVATARS.map(a=>`<button class="kid ${a===(state.kids[0].avatar||"🐯")?"on":""}" onclick="state.kids[0].avatar='${a}';renderOnboard()"><div class="avatar">${a}</div></button>`).join("");}
function finishOnboard(){const n=(document.getElementById("onName").value||"").trim();if(!n){bang("Name?",false);return;}state.kids[0].name=n;state.onboarded=true;save();show("home");}
function beltIndex(id){return BELTS.findIndex(b=>b.id===id);}
function renderHome(){const chip=document.getElementById("kidChip");if(chip)chip.textContent=kid().avatar+" "+kid().name;document.getElementById("kidList").innerHTML=state.kids.map((k,i)=>`<button class="kid ${i===state.active?"on":""}" onclick="pickKid(${i})"><div class="avatar">${k.avatar}</div><b>${k.name}</b><small>${BELTS.find(b=>b.id===k.belt).name} belt</small></button>`).join("");document.getElementById("beltStrip").innerHTML=BELTS.map(b=>{const have=beltIndex(kid().belt)>=beltIndex(b.id);return `<div class="belt ${!have?"locked":""}" style="background:${b.color};color:${b.id==="white"||b.id==="yellow"?"#221":"#fff"}">${b.name}${!have?" 🔒":""}<br>${b.skill}</div>`;}).join("");const days=["M","T","W","T","F","S","S"];const ws=weekStart();const cal=document.getElementById("calStrip");if(cal)cal.innerHTML=days.map((lab,i)=>{const key=new Date(ws+i*86400000).toISOString().slice(0,10);const on=!!(kid().stamps||{})[key];return `<div style="width:36px;text-align:center;background:${on?"#146a38":"#2a141a"};border-radius:10px;padding:6px"><b>${lab}</b></div>`;}).join("");}
function pickKid(i){state.active=i;save();renderHome();}
function renderEdit(){document.getElementById("editFields").innerHTML=state.kids.map((k,i)=>`<div class="card"><div class="row"><input value="${k.name}" onchange="state.kids[${i}].name=this.value" /><select onchange="state.kids[${i}].avatar=this.value">${AVATARS.map(a=>`<option ${a===k.avatar?"selected":""}>${a}</option>`).join("")}</select></div></div>`).join("");}
function saveKids(){save();show("home");}
function factKey(kind,a,b){if(kind==="A")return"A:"+a+"+"+b;if(kind==="S")return"S:"+a+"-"+b;return"M:"+a+"x"+b;}
function markFact(key,ok){const f=kid().facts;if(f[key]==null)f[key]=0;f[key]=ok?Math.min(5,f[key]+1):Math.max(0,f[key]-2);}
function levelOf(n){return n>=3?"m":n>=1?"s":"u";}
function makeProblem(band,trick){const k=kid();const pool=[];const push=(kind,a,b,ans,text,extraKey)=>{const key=extraKey||factKey(kind,a,b);const lv=k.facts[key]||0;pool.push({kind,a,b,ans,text,key,w:lv>=3?1:lv>=1?4:5});};
if(band==="white"){for(let a=0;a<=20;a++)for(let b=0;b<=20-a;b++)push("A",a,b,a+b,a+" + "+b);for(let a=0;a<=20;a++)for(let b=0;b<=a;b++)push("S",a,b,a-b,a+" − "+b);}
else if(band==="yellow"){for(let a=1;a<=12;a++)for(let b=1;b<=5;b++)push("M",a,b,a*b,a+" × "+b);}
else if(band==="orange"){for(let a=1;a<=12;a++)for(let b=6;b<=9;b++)push("M",a,b,a*b,a+" × "+b);if(trick){const a=1+Math.floor(Math.random()*12);const b=6+Math.floor(Math.random()*4);return{kind:"M",a,b,ans:a*b,text:a+" × "+b+" (not +)",key:factKey("M",a,b),trick:true,decoy:a+b};}}
else if(band==="green"){for(let a=1;a<=12;a++)for(let b=10;b<=12;b++)push("M",a,b,a*b,a+" × "+b);}
else if(band==="blue"){for(let a=1;a<=12;a++)for(let b=1;b<=12;b++)push("D",a*b,a,b,(a*b)+" ÷ "+a,"D:"+(a*b)+"/"+a);}
else if(band==="purple"){const dens=[2,3,4];for(const d of dens)for(let n=2;n<=12;n++)if(n%d===0)push("F",n,d,n/d,n+" × 1/"+d,"F:"+n+"/1/"+d);}
else if(band==="brown"){for(let a=11;a<=19;a++)for(let b=2;b<=9;b++)push("W",a,b,a*b,a+" × "+b,"W:"+a+"x"+b);}
else{const mix=["yellow","orange","green","blue","purple","brown"];return makeProblem(mix[Math.floor(Math.random()*mix.length)],trick);}
if(!pool.length)return makeProblem("yellow",false);let total=pool.reduce((s,p)=>s+p.w,0);let r=Math.random()*total;for(const p of pool){r-=p.w;if(r<=0)return p;}return pool[pool.length-1];}
function choices(p){const set=new Set([p.ans]);if(p.decoy!=null)set.add(p.decoy);while(set.size<4){const span=Math.max(6,Math.round(Math.abs(p.ans)*0.2));const d=p.ans+Math.floor(Math.random()*(span*2+1))-span;if(d!==p.ans&&d>=0)set.add(d);}return[...set].sort(()=>Math.random()-.5);}
function currentBand(){return kid().belt||"yellow";}
function startTrain(){play={mode:"train",band:currentBand(),start:Date.now(),limit:10*60*1000,correct:0,wrong:0,combo:0,best:0,timer:null};show("play");document.getElementById("playTitle").textContent="Daily Training · "+currentBand().toUpperCase();nextQ();tick();play.timer=setInterval(tick,250);}
function tick(){if(!play||play.mode!=="train")return;const left=Math.max(0,play.limit-(Date.now()-play.start));const s=Math.ceil(left/1000);document.getElementById("playMeta").textContent=Math.floor(s/60)+":"+String(s%60).padStart(2,"0");if(left<=0)endPlay(true);}
function startBoss(){const band=currentBand();play={mode:"boss",band,next:nextBeltId(kid().belt),start:Date.now(),correct:0,wrong:0,combo:0,best:0,lives:band==="white"?3:null,need:band==="white"?20:null,limit:band==="white"?null:90*1000,timer:null};show("play");document.getElementById("playTitle").textContent="BOSS · "+band.toUpperCase();nextQ(true);if(play.limit){play.timer=setInterval(()=>{const left=Math.max(0,play.limit-(Date.now()-play.start));const s=Math.ceil(left/1000);document.getElementById("playMeta").textContent=s+"s · "+play.correct+" hits";if(left<=0)endPlay(true);},200);}else document.getElementById("playMeta").textContent=play.lives+" lives · "+play.correct+"/"+play.need;}
function nextBeltId(id){const i=beltIndex(id);return BELTS[Math.min(BELTS.length-1,i+1)].id;}
function nextQ(boss){play.q=makeProblem(play.band,boss&&play.band==="orange"&&Math.random()<0.28);document.getElementById("problem").textContent=play.q.text;document.getElementById("streakLine").textContent="COMBO x"+play.combo;document.getElementById("comboBar").style.width=Math.min(100,play.combo*10)+"%";document.getElementById("answers").innerHTML=choices(play.q).map(n=>`<button class="ans" onclick="answer(${n})">${n}</button>`).join("");}
function bang(text,good){const el=document.getElementById("fx");el.textContent=text;el.style.color=good?"#3dff8a":"#ff3b4a";el.classList.remove("show");void el.offsetWidth;el.classList.add("show");}
function answer(n){if(!play||play.lock)return;play.lock=true;const ok=n===play.q.ans;markFact(play.q.key,ok);document.querySelectorAll(".ans").forEach(b=>{const v=Number(b.textContent);if(v===play.q.ans)b.classList.add("good");if(v===n&&!ok)b.classList.add("bad");});if(ok){play.correct++;play.combo++;play.best=Math.max(play.best,play.combo);bang(play.combo>=5?"COMBO!":"HIT!",true);}else{play.wrong++;play.combo=0;bang("WHIFF!",false);if(play.mode==="boss"&&play.lives!=null){play.lives--;document.getElementById("playMeta").textContent=play.lives+" lives · "+play.correct+"/"+play.need;if(play.lives<=0){setTimeout(()=>endPlay(true),400);return;}}}if(play.mode==="boss"&&play.need&&play.correct>=play.need){setTimeout(()=>endPlay(true),400);return;}if(play.mode==="spar"){play.scores[play.turn]+=ok?1:0;play.round++;if(play.round>=8){play.turn=play.turn===0?1:0;play.round=0;if(play.turn===0&&play.pass){setTimeout(()=>endPlay(true),400);return;}if(play.turn===1)play.pass=true;bang((play.turn===0?play.names[0]:play.names[1])+" GO",true);}}setTimeout(()=>{play.lock=false;nextQ(play.mode==="boss");},350);}
function endPlay(done){if(!play)return;if(play.timer)clearInterval(play.timer);const k=kid();if(done&&play.mode!=="spar"){k.minutes+=play.mode==="train"?10:2;k.comboBest=Math.max(k.comboBest||0,play.best);k.stamps[new Date().toISOString().slice(0,10)]=true;k.sessions.push({t:Date.now(),mode:play.mode,correct:play.correct,wrong:play.wrong});if(play.mode==="boss"){const needHits=play.band==="yellow"?18:play.band==="orange"?16:14;const pass=play.need?play.correct>=play.need&&play.lives>0:play.correct>=needHits;if(pass){k.belt=play.next;save();finish("Belt ceremony!","🏆",k.name+" is now "+BELTS.find(b=>b.id===k.belt).name+" belt.");play=null;return;}}save();}if(play.mode==="spar"){const a=play.scores[0],b=play.scores[1];finish("Spar complete","⚔️",a===b?"Draw! "+a+"–"+b:(a>b?play.names[0]:play.names[1])+" wins");play=null;return;}finish(done?"Training stamped":"Paused",done?"🔥":"⏸️",play.correct+" hits · combo x"+play.best);play=null;}
function finish(title,emoji,body){document.getElementById("resultTitle").textContent=title;document.getElementById("resultEmoji").textContent=emoji;document.getElementById("resultBody").textContent=body;show("result");}
function renderSparSetup(){const k=kid();document.getElementById("p1").innerHTML=`<option>${k.avatar} ${k.name}</option>`;document.getElementById("p2").innerHTML=`<option>Parent / challenger</option>`;}
function startSpar(){play={mode:"spar",band:document.getElementById("sparBelt").value,start:Date.now(),correct:0,wrong:0,combo:0,best:0,names:[kid().name,"Challenger"],scores:[0,0],turn:0,round:0,pass:false};show("play");document.getElementById("playTitle").textContent="SPAR";nextQ();}
function showParentGate(){document.getElementById("pinIn").value="";show("parentGate");}
function unlockParent(){if(document.getElementById("pinIn").value===state.pin)show("parent");else bang("Nope",false);}
function weekStart(){const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d.getTime();}
function renderParent(){const sel=document.getElementById("parentKid");sel.innerHTML=state.kids.map((k,i)=>`<option value="${i}">${k.name}</option>`).join("");const k=state.kids[+sel.value||0];const ws=weekStart();const sess=(k.sessions||[]).filter(s=>s.t>=ws);document.getElementById("weekStats").innerHTML=`<div>Belt: ${BELTS.find(b=>b.id===k.belt).name}</div><div>Days: ${Object.keys(k.stamps||{}).filter(d=>new Date(d).getTime()>=ws).length}</div><div>Sessions: ${sess.length}</div>`;let html="<table class='heat'><tr><th>×</th>";for(let b=1;b<=9;b++)html+="<th>"+b+"</th>";html+="</tr>";for(let a=1;a<=12;a++){html+="<tr><th>"+a+"</th>";for(let b=1;b<=9;b++){const n=k.facts["M:"+a+"x"+b]||0;html+=`<td class="${levelOf(n)}">${n}</td>`;}html+="</tr>";}html+="</table>";document.getElementById("heatWrap").innerHTML=html;const rp=document.getElementById("reportPreview");if(rp)rp.textContent=weeklyText(k);const fb=document.getElementById("forceBelt");if(fb)fb.innerHTML=BELTS.map(b=>`<option value="${b.id}" ${b.id===k.belt?"selected":""}>${b.name}</option>`).join("");}
function forceBelt(id){kid().belt=id;save();bang(id+" belt",true);}
function weeklyText(k){return k.name+" · "+BELTS.find(b=>b.id===k.belt).name+" belt · "+(k.minutes||0)+" min";}
function copyReport(){navigator.clipboard.writeText(weeklyText(kid())).then(()=>bang("Copied",true));}
function mailReport(){location.href="mailto:?subject=Math Dojo&body="+encodeURIComponent(weeklyText(kid()));}
function renderDrops(){const stamps=Object.keys(kid().stamps||{}).length;document.getElementById("dropList").innerHTML=DROPS.map((d,i)=>{const open=i===0||stamps>=i*3;const on=(kid().drop||"mat-red")===d.id;return `<div class="card" style="margin-bottom:10px;opacity:${open?1:.45}"><b>${d.name}</b> · ${d.when}<br>${d.desc}${open?`<button class="btn ${on?"gold":""} wide" onclick="equipDrop('${d.id}')">${on?"Equipped":"Equip"}</button>`:""}</div>`;}).join("");}
function equipDrop(id){kid().drop=id;save();const d=DROPS.find(x=>x.id===id);document.body.style.background=`radial-gradient(1200px 600px at 50% -10%, ${d.ground} 0%, transparent 55%), #12060a`;renderDrops();bang("New ground",true);}
if(!state.onboarded||!kid().name)show("onboard");else show("home");
